# Generated by Django 4.2.5 on 2026-04-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0005_tag_entry_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': 'Профиль автора', 'verbose_name_plural': 'Авторские профили'},
        ),
    ]
